job table ,job details, event table
eduCyber-HRmagazine/adminDashboard-frontend pull request #6
Opened 2024-03-22 03:17 UTC by Shimaa-Mahmoud-Abdelazeem

2024-03-22 06:55 UTC, Nora-Lootfy commented on src/pages/Events/event-details.html
> +            <h1 class="pt-5">Event Details</h1>
This is the first thing, i have noticed in your code.

Take it as an advice from me, don't ever make two h1 tag in your design, This is considered as bad practice. 
A little trick, if you want to display it as h1 use bootstrap class. 

Actually i like to display it a little smaller, The following code snippet looks much better
 ```html
<h2 class="pt-5  fw-bold">Event Details</h2>
```

2024-03-22 09:00 UTC, Nora-Lootfy requested changes
Hello Shimaa,

Thanks for your hard working, very obvious for me that you have worked a lot.

I have left some comments for you, and add little tweaks that i forget to mention in the task so please replace them and make another pull request. 

Another thing about naming, I like to make all my files working with the same naming convention not just the code, so please lowercase the folder or files if you make any of them upper case.

I have also notice that you don't indent your code properly, but it is actually simple and make your code more neat, there is a plugin or extension called Prettier that formats your code just download and when you want to format your code press ctrl + alt + f

Last thing, I feel very comfortable when i see your pages, looks so pretty for me so thanks again.

I am pretty confident, we have amazing frontend developer 😊✨
Thanks ya Shimaa

[frontend.zip](https://github.com/eduCyber-HRmagazine/adminDashboard-frontend/files/14720058/frontend.zip)

2024-03-22 09:00 UTC, Nora-Lootfy commented on src/pages/Events/events.html
> +          <h1 class="pt-5">Events</h1>
Same as event details

2024-03-22 09:00 UTC, Nora-Lootfy commented on src/pages/Events/events.html
> +          <div class="row py-2">
Actually i prefer that search is on the same line as heading, use the code snippet
```html
<div class="row py-3 justify-content-between align-items-center">
              <h2 class="fw-bold col-lg-auto">Events</h2>
              <div class="col-lg-auto">
                <!-- Search Bar start -->
                <div class="search-bar">
                  <form action="">
                    <div
                      class="row g-1 justify-content-lg-end justify-content-start"
                    >
                      <div class="col-6 col-lg-3 form-floating">
                        <input type="text" class="form-control" id="title" />
                        <label for="title">Event title</label>
                      </div>
                      <div class="col-6 col-lg-3 form-floating">
                        <input type="date" class="form-control" id="date" />
                        <label for="date">Start date</label>
                      </div>
                      <div class="col-6 col-lg-3 form-floating">
                        <select class="form-control bg-white">
                          <option>-</option>
                          <option>categroy #1</option>
                          <option>categroy #2</option>
                          <option>categroy #3</option>
                          <option>categroy #4</option>
                        </select>
                        <label for="date">Select Category</label>
                      </div>
                      <button
                        class="col-auto btn border-0 btn-md"
                        type="submit"
                      >
                        <i class="icon-search fs-5"></i>
                      </button>
                    </div>
                  </form>
                </div>
                <!-- Search Bar ends -->
              </div>
            </div>
```

2024-03-22 09:00 UTC, Nora-Lootfy commented on src/pages/Events/events.html
> +                  <div class="table-responsive content">
Actually, I like that you care a lot about responsive design, thanks for that

pretty cool, table😊

2024-03-22 19:55 UTC, Shimaa-Mahmoud-Abdelazeem commented
Thank you alot Nora for your comments, advice and encouraging words .
I will make all of changes that you are mentioned and push my code again.

2024-03-23 06:11 UTC, Nora-Lootfy approved these changes

2024-03-23 06:11 UTC, merged